name: Get Input (Test)

on:
  workflow_dispatch:
    inputs:
      months:
        # type: choice
        description: How many months to go back
        # options: 
        # - 1
        # - 2
        # - 3
        # default: 1

jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
      - name: Install Dependencies
        run: npm ci
      - name: Echo env
        run: env
      - name: Run Logger
        run: npm run get-input-test
