name: Get Input (Test)

on:
  workflow_dispatch:
    inputs:
      months:
        type: choice
        description: How many months to go back
        options: 
        - 1
        - 2
        - 3
        default: 1

jobs:
  logger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
      - name: Install Dependencies
        run: npm ci
      - name: Echo env
        run: env
      - name: Run Logger
        run: npm run get-input-test
        # Note:
        # inputs: で注入した値は `INPUT_` という接頭辞がついて環境変数にセットされるとのことだったが、 されない場合がある。
        # https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs
        # > If the action is written using a composite, then it will not automatically get INPUT_<VARIABLE_NAME>. If the conversion doesn't occur, you can change these inputs manually.
        # そのためこちらで紹介されているように明示的にセットするワークアラウンドが必要。
        # https://github.com/actions/runner/issues/665#issuecomment-1886156288
        # todo: なぜこのactionが `composite action` として扱われているのかを理解する。
        env:
          INPUT_MONTHS: ${{ github.event.inputs.months }}
