name: Run Crawler (production)

on:
  schedule:
    # 毎朝10時
    - cron: '0 10 * * *'

jobs:
  crawl:
    runs-on: ubuntu-latest
    env:
      LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
      LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.15.0'
      - name: Install Dependencies
        run: npm ci
      - name: Run Crawler
        run: npm run main:prd
