name: Run Crawler (production)

on:
  schedule:
    # 毎月1日の19時
    - cron: '0 10 1 * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.15.0'
      - name: Install Dependencies
        run: npm ci
      - name: Run Crawler
        run: npm run main:prd
        # note: GitHub Actions 上でスクリーンショットを取る際にコメントアウト
        # continue-on-error: true
        env:
          LOGIN_EMAIL: ${{ secrets.LOGIN_EMAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
      # note: GitHub Actions 上でスクリーンショットを取る際にコメントアウト
      # - name: Download screenshot
      #   uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: screenshot
      #     path: tmp/
